Ensure that Parent ID is empty if and only if the category is top-level
InteractiveAdvertisingBureau/Taxonomies pull request #37
Opened 2024-07-08 13:28 UTC by hedgeho

This PR makes small fixes to "Content Taxonomy 3.0.tsv" to ensure consistent hierarchy. In particular, it ensures that Parent ID is empty if and only if the category is top-level.

See automated checks at https://github.com/c-wire/IAB-taxonomies/blob/main/validate_IAB_categories.py

2024-07-08 13:30 UTC, hedgeho commented
@katieshell 
As you are an active contributor to this repository, could you review this PR? Thanks.

2025-02-28 19:26 UTC, gg-aking commented
Any reason this can't be merged?

2025-03-03 20:37 UTC, keishingg commented
@hedgeho Could you apply the same changes to "Content Taxonomy 3.0.tsv" as well?

2025-03-04 14:17 UTC, hedgeho commented
Merged updates and ran the checks against "Content Taxonomy 3.1.tsv"

2025-03-12 12:08 UTC, Kiam-Venter-001 requested changes
Perfect changes, one last change that needs to be made is that of Public Radio (row 232 of tsv file), as it still has the Parent ID of Genres, not of Talk Radio (so the Parent ID of Public Radio should change from SPSHQ5 to 371).

This should be done in addition to these already listed changes.

2025-03-12 19:36 UTC, katieshell approved these changes

2025-03-12 19:37 UTC, merged